name: Trigger auto deployment for containerapp gotham

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/gotham-AutoDeployTrigger-d0958391-4d76-4518-b7df-9327cab16989.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: wpdacr.azurecr.io
          username: ${{ secrets.GOTHAM_REGISTRY_USERNAME }}
          password: ${{ secrets.GOTHAM_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wpdacr.azurecr.io/gotham:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GOTHAM_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n gotham -g DefaultResourceGroup-WEU --server wpdacr.azurecr.io --username  ${{ secrets.GOTHAM_REGISTRY_USERNAME }} --password ${{ secrets.GOTHAM_REGISTRY_PASSWORD }}
            az containerapp update -n gotham -g DefaultResourceGroup-WEU --image wpdacr.azurecr.io/gotham:${{ github.sha }}
